Repository iutzeler/skwdro, pull requests merged in 2024-11, with the labels that each got.

#134 FIX: Let Dirac code abide to Liskov substitution principle
  pyproject.toml
  skwdro/distributions/dirac_distribution.py
Labels: bug, Test

#129 [DEV->MAIN] Important updates
  CITATION.bib
  CODE_OF_CONDUCT.md
  Makefile
  README.md
  examples/builtin_models/logistic_regression.py
  examples/builtin_models/utils/classifier_comparison.py
  pyproject.toml
  skwdro/distributions/dirac_distribution.py
  skwdro/solvers/_dual_interfaces/_impsamp_interface.py
  skwdro/solvers/_dual_interfaces/_misc_dual_interfaces.py
  skwdro/solvers/utils.py
  tests/misc/launchall.sh
Labels: Discussion

#141 Release for multiclass WDRO classification
  skwdro/_version.py
Labels: release

#146 Customize learning rate of some estimators.
  pyproject.toml
  skwdro/linear_models/_linear_regression.py
  skwdro/linear_models/_logistic_regression.py
  skwdro/operations_research/_newsvendor.py
  skwdro/operations_research/_portfolio.py
  skwdro/operations_research/_weber.py
  skwdro/solvers/oracle_torch.py
  skwdro/wrap_problem.py
Labels: enhancement

#148 Release: 1.1.1
  skwdro/_version.py
Labels: release
